Add types alpha
SwedbankPay/swedbank-pay-sdk-js pull request #341
Opened 2021-06-28 18:44 UTC by NullableInt

#336 but with base as main
@Xillians this is your playground, contact me if help is needed.

2021-07-07 20:39 UTC, cobraz reviewed
AFAIK, this are all the types for the full API?

2021-07-08 07:34 UTC, NullableInt commented
> AFAIK, these are all the types for the full API?

Yes, I've ported all types from the .Net SDK. I have still to fix the build error.

2022-01-26 14:03 UTC, asbjornu requested changes

2022-01-26 14:03 UTC, asbjornu commented on package.json
>    "author": "Bjerk AS <office@bjerk.io>",
```suggestion
  "author": "Swedbank Pay <opensource@swedbankpay.com>",
```

2022-01-28 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-js?pullRequest=341) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/swedbank-pay-sdk-js?pullRequest=341) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Xillians<br/>:x: Syver<br/><hr/>**Syver** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/swedbank-pay-sdk-js?pullRequest=341) it.</sub>

2022-05-24 10:44 UTC, Xillians approved these changes

2022-05-24 12:02 UTC, NullableInt commented
Looks like we are getting close to something great!
@asbjornu should approve, perhaps we should bribe him?

2022-06-03 20:25 UTC, asbjornu commented
Where do I collect my bribe?

2022-06-06 15:02 UTC, NullableInt commented
> Where do I collect my bribe?

Have your guys connect with my guys, and we'll have it delivered at the usual drop of point.

2022-06-07 10:09 UTC, merged